const filmsData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/IYUD7rAIXzBM91TT3Z5fILUS7n.jpg",
      genre_ids: [80, 9648, 53],
      id: 414906,
      original_language: "en",
      original_title: "The Batman",
      overview:
        "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
      popularity: 878.834,
      poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
      release_date: "2022-03-01",
      title: "The Batman",
      video: false,
      vote_average: 7.8,
      vote_count: 5520,
    },
    {
      adult: false,
      backdrop_path: "/2va32apQP97gvUxaMnL5wYt4CRB.jpg",
      genre_ids: [14, 28],
      id: 268,
      original_language: "en",
      original_title: "Batman",
      overview:
        'Batman must face his most ruthless nemesis when a deformed madman calling himself "The Joker" seizes control of Gotham\'s criminal underworld.',
      popularity: 47.646,
      poster_path: "/kbeWnmnHNEnuVej6wcjUv0eY6IL.jpg",
      release_date: "1989-06-23",
      title: "Batman",
      video: false,
      vote_average: 7.2,
      vote_count: 6376,
    },
    {
      adult: false,
      backdrop_path: "/hQrHN6WXERVw6XUMpfCgLfvrh5V.jpg",
      genre_ids: [28, 80, 18],
      id: 272,
      original_language: "en",
      original_title: "Batman Begins",
      overview:
        "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.",
      popularity: 55.952,
      poster_path: "/8RW2runSEc34IwKN2D1aPcJd2UL.jpg",
      release_date: "2005-06-10",
      title: "Batman Begins",
      video: false,
      vote_average: 7.7,
      vote_count: 17883,
    },
    {
      adult: false,
      backdrop_path: "/eevJuYAitUe6VwFN29aFwzeyeTr.jpg",
      genre_ids: [878, 80, 16, 9648, 28],
      id: 537056,
      original_language: "en",
      original_title: "Batman: Hush",
      overview:
        "A mysterious new villain known only as Hush uses a gallery of villains to destroy Batman's crime-fighting career as well as Bruce Wayne's personal life, which has been further complicated by a relationship with Selina Kyle/Catwoman.",
      popularity: 28.847,
      poster_path: "/eiVQORVyVuNNZHPAELuWtlXoQsD.jpg",
      release_date: "2019-07-19",
      title: "Batman: Hush",
      video: false,
      vote_average: 7.3,
      vote_count: 657,
    },
    {
      adult: false,
      backdrop_path: "/fsJgRuXzNnnXk5IVwVbBPdavaNX.jpg",
      genre_ids: [28, 14],
      id: 364,
      original_language: "en",
      original_title: "Batman Returns",
      overview:
        "While Batman deals with a deformed man calling himself the Penguin, an employee of a corrupt businessman transforms into the Catwoman.",
      popularity: 35.056,
      poster_path: "/jKBjeXM7iBBV9UkUcOXx3m7FSHY.jpg",
      release_date: "1992-06-19",
      title: "Batman Returns",
      video: false,
      vote_average: 6.9,
      vote_count: 5322,
    },
    {
      adult: false,
      backdrop_path: "/snlu32RmjldF9b068UURJg8sQtn.jpg",
      genre_ids: [28, 80, 14],
      id: 414,
      original_language: "en",
      original_title: "Batman Forever",
      overview:
        "Batman must battle a disfigured district attorney and a disgruntled former employee with help from an amorous psychologist and a young circus acrobat.",
      popularity: 34.308,
      poster_path: "/mzzNBVwTiiY94xAXDMWJpNPW2US.jpg",
      release_date: "1995-06-16",
      title: "Batman Forever",
      video: false,
      vote_average: 5.4,
      vote_count: 4330,
    },
    {
      adult: false,
      backdrop_path: "/kU7ZiyeUwcpTkYj3UcxSqGdZmxY.jpg",
      genre_ids: [16, 28],
      id: 618353,
      original_language: "en",
      original_title: "Batman: Death in the Family",
      overview:
        "Tragedy strikes the Batman's life again when Robin Jason Todd tracks down his birth mother only to run afoul of the Joker. An adaptation of the 1988 comic book storyline of the same name.",
      popularity: 68.264,
      poster_path: "/k8Q9ulyRE8fkvZMkAM9LPYMKctb.jpg",
      release_date: "2020-10-13",
      title: "Batman: Death in the Family",
      video: false,
      vote_average: 7.3,
      vote_count: 336,
    },
    {
      adult: false,
      backdrop_path: "/nwfpBjtMNFwrGjW2o9HBhMEYCpM.jpg",
      genre_ids: [878, 28, 16],
      id: 366924,
      original_language: "en",
      original_title: "Batman: Bad Blood",
      overview:
        "Bruce Wayne is missing. Alfred covers for him while Nightwing and Robin patrol Gotham City in his stead and a new player, Batwoman, investigates Batman's disappearance.",
      popularity: 28.977,
      poster_path: "/1UmPJWfaivtNjsScJqcsbsQRGNY.jpg",
      release_date: "2016-08-04",
      title: "Batman: Bad Blood",
      video: false,
      vote_average: 7.2,
      vote_count: 604,
    },
    {
      adult: false,
      backdrop_path: "/m4UT6yKXhXgbzxpeV35L4jLoJoP.jpg",
      genre_ids: [878, 28, 14],
      id: 415,
      original_language: "en",
      original_title: "Batman & Robin",
      overview:
        "Batman and Robin deal with relationship issues while preventing Mr. Freeze and Poison Ivy from attacking Gotham City.",
      popularity: 29.096,
      poster_path: "/cGRDufDDSrFrv7VI4YnmWnslne0.jpg",
      release_date: "1997-06-20",
      title: "Batman & Robin",
      video: false,
      vote_average: 4.3,
      vote_count: 4205,
    },
    {
      adult: false,
      backdrop_path: "/doiUtOHzcxXFl0GVQ2n8Ay6Pirx.jpg",
      genre_ids: [28, 12, 14],
      id: 209112,
      original_language: "en",
      original_title: "Batman v Superman: Dawn of Justice",
      overview:
        "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
      popularity: 78.603,
      poster_path: "/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
      release_date: "2016-03-23",
      title: "Batman v Superman: Dawn of Justice",
      video: false,
      vote_average: 5.9,
      vote_count: 15946,
    },
    {
      adult: false,
      backdrop_path: "/4aJPdkPLnLiiCbfu6WFUQzER3u0.jpg",
      genre_ids: [878, 28, 12, 16],
      id: 321528,
      original_language: "en",
      original_title: "Batman vs. Robin",
      overview:
        'Damian Wayne is having a hard time coping with his father\'s "no killing" rule. Meanwhile, Gotham is going through hell with threats such as the insane Dollmaker, and the secretive Court of Owls.',
      popularity: 26.19,
      poster_path: "/aGp9XDXmVM5lCKHWtgBC15S7XLr.jpg",
      release_date: "2015-04-14",
      title: "Batman vs. Robin",
      video: false,
      vote_average: 7.2,
      vote_count: 746,
    },
    {
      adult: false,
      backdrop_path: "/4p9MrndEp154yxknw0WOwr3VaVq.jpg",
      genre_ids: [16, 28, 35, 10751],
      id: 324849,
      original_language: "en",
      original_title: "The Lego Batman Movie",
      overview:
        "A cooler-than-ever Bruce Wayne must deal with the usual suspects as they plan to rule Gotham City, while discovering that he has accidentally adopted a teenage orphan who wishes to become his sidekick.",
      popularity: 42.986,
      poster_path: "/snGwr2gag4Fcgx2OGmH9otl6ofW.jpg",
      release_date: "2017-02-08",
      title: "The Lego Batman Movie",
      video: false,
      vote_average: 7.2,
      vote_count: 4176,
    },
    {
      adult: false,
      backdrop_path: "/nOWOU0bdX76iF9XA1YPlInLbI4Y.jpg",
      genre_ids: [10751, 12, 35, 878, 80],
      id: 2661,
      original_language: "en",
      original_title: "Batman",
      overview:
        "The Dynamic Duo faces four super-villains who plan to hold the world for ransom with the help of a secret invention that instantly dehydrates people.",
      popularity: 15.291,
      poster_path: "/jV4grL9Sxd2QA6oCOyIzdmVAJvp.jpg",
      release_date: "1966-07-30",
      title: "Batman",
      video: false,
      vote_average: 6.3,
      vote_count: 667,
    },
    {
      adult: false,
      backdrop_path: "/jvRewPpawHAfBW38EzHoFdTVEez.jpg",
      genre_ids: [16, 28, 12, 80, 14],
      id: 732450,
      original_language: "en",
      original_title: "Batman: Soul of the Dragon",
      overview:
        "Bruce Wayne faces a deadly menace from his past, with the help of three former classmates: world-renowned martial artists Richard Dragon, Ben Turner and Lady Shiva.",
      popularity: 43.197,
      poster_path: "/uDhnTtSxU5a8DtZdbbin3aZmkmU.jpg",
      release_date: "2021-01-12",
      title: "Batman: Soul of the Dragon",
      video: false,
      vote_average: 7.1,
      vote_count: 243,
    },
    {
      adult: false,
      backdrop_path: "/otumLIRpsQqy4gROSGQ8LjxHGsL.jpg",
      genre_ids: [878, 28, 12, 16, 10751],
      id: 45162,
      original_language: "en",
      original_title: "Superman/Batman: Apocalypse",
      overview:
        "Batman discovers a mysterious teen-aged girl with superhuman powers and a connection to Superman. When the girl comes to the attention of Darkseid, the evil overlord of Apokolips, events take a decidedly dangerous turn.",
      popularity: 28.578,
      poster_path: "/d7gHmsA2o5Z1MhcuspMyOSO48KB.jpg",
      release_date: "2010-09-28",
      title: "Superman/Batman: Apocalypse",
      video: false,
      vote_average: 7.2,
      vote_count: 544,
    },
    {
      adult: false,
      backdrop_path: "/j14Z0pP7tpuHZlVBSuUL7tq2SGb.jpg",
      genre_ids: [16, 9648, 28, 80],
      id: 736074,
      original_language: "en",
      original_title: "Batman: The Long Halloween, Part Two",
      overview:
        "As Gotham City's young vigilante, the Batman, struggles to pursue a brutal serial killer, district attorney Harvey Dent gets caught in a feud involving the criminal family of the Falcones.",
      popularity: 59.118,
      poster_path: "/5X1n5q08mZ7NpNpxehMFODxfNYq.jpg",
      release_date: "2021-07-26",
      title: "Batman: The Long Halloween, Part Two",
      video: false,
      vote_average: 7.6,
      vote_count: 337,
    },
    {
      adult: false,
      backdrop_path: "/bAM1hVZEQRo1ZujryQ47bOtxEe8.jpg",
      genre_ids: [53, 16, 28, 80],
      id: 242643,
      original_language: "en",
      original_title: "Batman: Assault on Arkham",
      overview:
        "Batman works desperately to find a bomb planted by the Joker while Amanda Waller sends her newly-formed Suicide Squad to break into Arkham Asylum and recover vital information stolen by the Riddler.",
      popularity: 28.727,
      poster_path: "/mmQZekxr9gJ7c0Grkx6xgKvrpDy.jpg",
      release_date: "2014-08-12",
      title: "Batman: Assault on Arkham",
      video: false,
      vote_average: 7.4,
      vote_count: 927,
    },
    {
      adult: false,
      backdrop_path: "/ng7VxyF0xl2d7ApM7Jo3lvH2LkG.jpg",
      genre_ids: [878, 16, 28, 12],
      id: 13851,
      original_language: "en",
      original_title: "Batman: Gotham Knight",
      overview:
        "A collection of key events mark Bruce Wayne's life as he journeys from beginner to Dark Knight.",
      popularity: 18.308,
      poster_path: "/weCFATAA8ntBRRgLkIcbz4EFsLl.jpg",
      release_date: "2008-07-08",
      title: "Batman: Gotham Knight",
      video: false,
      vote_average: 6.7,
      vote_count: 516,
    },
    {
      adult: false,
      backdrop_path: "/ofC1u2mYUWdZI3RxLW4dBvh9Q39.jpg",
      genre_ids: [28, 16, 80, 18],
      id: 382322,
      original_language: "en",
      original_title: "Batman: The Killing Joke",
      overview:
        "As Batman hunts for the escaped Joker, the Clown Prince of Crime attacks the Gordon family to prove a diabolical point mirroring his own fall into madness.",
      popularity: 25.144,
      poster_path: "/nxncAAL1FUKtQWs4uhs5jf1MVut.jpg",
      release_date: "2016-07-24",
      title: "Batman: The Killing Joke",
      video: false,
      vote_average: 6.6,
      vote_count: 1492,
    },
    {
      adult: false,
      backdrop_path: "/uS9apevOgs2fuYghf9szOoK1u63.jpg",
      genre_ids: [16, 9648, 28, 80],
      id: 736073,
      original_language: "en",
      original_title: "Batman: The Long Halloween, Part One",
      overview:
        "Following a brutal series of murders taking place on Halloween, Thanksgiving, and Christmas, Gotham City's young vigilante known as the Batman sets out to pursue the mysterious serial killer alongside police officer James Gordon and district attorney Harvey Dent.",
      popularity: 48.063,
      poster_path: "/sR7gppb0YGjwLvE6Vnj6wYv5MnW.jpg",
      release_date: "2021-06-21",
      title: "Batman: The Long Halloween, Part One",
      video: false,
      vote_average: 7.6,
      vote_count: 400,
    },
  ],
  total_pages: 7,
  total_results: 134,
};
export default filmsData;
